/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package payrollsystem;

import javax.swing.JOptionPane;

/**
 *
 * @author stefa
 */
public class EditEmployeeInfoGUI extends javax.swing.JFrame {

    private final EmployeeInfo employeeInfo = EmployeeInfo.getInstance();
    private final EmployeeDataFetcher dataFetcher = new EmployeeDataFetcher();
    private final EmployeeInfoUpdater updater = new EmployeeInfoUpdater();
    
    public EditEmployeeInfoGUI() {
        initComponents();
        dataFetcher.loadUserInformation("employee_id", "employee_logins", "employees");
        loadForm();
        subtitleLBL.setText("Hello, " + employeeInfo.getName());
        saveBTN.setVisible(false);
        cancelBTN.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        titleLBL = new javax.swing.JLabel();
        iconLBL = new javax.swing.JLabel();
        subtitleLBL = new javax.swing.JLabel();
        fNameLBL = new javax.swing.JLabel();
        idLBL = new javax.swing.JLabel();
        rateLBL = new javax.swing.JLabel();
        addressLBL = new javax.swing.JLabel();
        addressTF = new javax.swing.JTextField();
        idTF = new javax.swing.JTextField();
        phoneNoTF = new javax.swing.JTextField();
        fNameTF = new javax.swing.JTextField();
        hireDateLBL = new javax.swing.JLabel();
        emailLBL = new javax.swing.JLabel();
        positionLBL = new javax.swing.JLabel();
        emailTF = new javax.swing.JTextField();
        positionTF = new javax.swing.JTextField();
        rateTF = new javax.swing.JTextField();
        phoneNoLBL = new javax.swing.JLabel();
        hireDateTF = new javax.swing.JTextField();
        editBTN = new javax.swing.JButton();
        saveBTN = new javax.swing.JButton();
        lNameLBL = new javax.swing.JLabel();
        lNameTF = new javax.swing.JTextField();
        cancelBTN = new javax.swing.JButton();
        backBTN1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));

        jPanel2.setBackground(new java.awt.Color(235, 142, 39));

        titleLBL.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        titleLBL.setForeground(new java.awt.Color(255, 255, 255));
        titleLBL.setText("YOUR INFORMATION");

        iconLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payrollsystem/PAYROLL_LOGO_E.png"))); // NOI18N

        subtitleLBL.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        subtitleLBL.setForeground(new java.awt.Color(255, 255, 255));
        subtitleLBL.setText("Hello,");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLBL)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(subtitleLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 318, Short.MAX_VALUE)
                .addComponent(iconLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(iconLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(titleLBL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subtitleLBL)
                        .addGap(12, 12, 12)))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        fNameLBL.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        fNameLBL.setText("FIRST NAME:");

        idLBL.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        idLBL.setText("ID:");

        rateLBL.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        rateLBL.setText("RATE:");

        addressLBL.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        addressLBL.setText("ADDRESS:");

        addressTF.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        addressTF.setForeground(new java.awt.Color(81, 81, 81));
        addressTF.setBorder(null);
        addressTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusColour(evt);
            }
        });
        addressTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressTFActionPerformed(evt);
            }
        });

        idTF.setEditable(false);
        idTF.setBackground(new java.awt.Color(255, 255, 255));
        idTF.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        idTF.setForeground(new java.awt.Color(81, 81, 81));
        idTF.setBorder(null);
        idTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTFActionPerformed(evt);
            }
        });

        phoneNoTF.setEditable(false);
        phoneNoTF.setBackground(new java.awt.Color(255, 255, 255));
        phoneNoTF.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        phoneNoTF.setForeground(new java.awt.Color(81, 81, 81));
        phoneNoTF.setBorder(null);
        phoneNoTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusColour(evt);
            }
        });
        phoneNoTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNoTFActionPerformed(evt);
            }
        });

        fNameTF.setEditable(false);
        fNameTF.setBackground(new java.awt.Color(255, 255, 255));
        fNameTF.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        fNameTF.setForeground(new java.awt.Color(81, 81, 81));
        fNameTF.setBorder(null);
        fNameTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusColour(evt);
            }
        });
        fNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNameTFActionPerformed(evt);
            }
        });

        hireDateLBL.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        hireDateLBL.setText("HIRE DATE:");

        emailLBL.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        emailLBL.setText("EMAIL:");

        positionLBL.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        positionLBL.setText("POSITION:");

        emailTF.setEditable(false);
        emailTF.setBackground(new java.awt.Color(255, 255, 255));
        emailTF.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        emailTF.setForeground(new java.awt.Color(81, 81, 81));
        emailTF.setBorder(null);
        emailTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusColour(evt);
            }
        });
        emailTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTFActionPerformed(evt);
            }
        });

        positionTF.setEditable(false);
        positionTF.setBackground(new java.awt.Color(255, 255, 255));
        positionTF.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        positionTF.setForeground(new java.awt.Color(81, 81, 81));
        positionTF.setBorder(null);
        positionTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                positionTFActionPerformed(evt);
            }
        });

        rateTF.setEditable(false);
        rateTF.setBackground(new java.awt.Color(255, 255, 255));
        rateTF.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        rateTF.setForeground(new java.awt.Color(81, 81, 81));
        rateTF.setBorder(null);
        rateTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusColour(evt);
            }
        });
        rateTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rateTFActionPerformed(evt);
            }
        });

        phoneNoLBL.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        phoneNoLBL.setText("PHONE NO:");

        hireDateTF.setEditable(false);
        hireDateTF.setBackground(new java.awt.Color(255, 255, 255));
        hireDateTF.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        hireDateTF.setForeground(new java.awt.Color(81, 81, 81));
        hireDateTF.setBorder(null);
        hireDateTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hireDateTFActionPerformed(evt);
            }
        });

        editBTN.setBackground(new java.awt.Color(235, 142, 39));
        editBTN.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        editBTN.setForeground(new java.awt.Color(255, 255, 255));
        editBTN.setText("edit information");
        editBTN.setBorder(null);
        editBTN.setBorderPainted(false);
        editBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBTNActionPerformed(evt);
            }
        });

        saveBTN.setBackground(new java.awt.Color(0, 255, 0));
        saveBTN.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        saveBTN.setForeground(new java.awt.Color(255, 255, 255));
        saveBTN.setText("save");
        saveBTN.setBorder(null);
        saveBTN.setBorderPainted(false);
        saveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBTNActionPerformed(evt);
            }
        });

        lNameLBL.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lNameLBL.setText("LAST NAME:");

        lNameTF.setEditable(false);
        lNameTF.setBackground(new java.awt.Color(255, 255, 255));
        lNameTF.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lNameTF.setForeground(new java.awt.Color(81, 81, 81));
        lNameTF.setBorder(null);
        lNameTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusColour(evt);
            }
        });
        lNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lNameTFActionPerformed(evt);
            }
        });

        cancelBTN.setBackground(new java.awt.Color(255, 0, 0));
        cancelBTN.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        cancelBTN.setForeground(new java.awt.Color(255, 255, 255));
        cancelBTN.setText("cancel");
        cancelBTN.setBorder(null);
        cancelBTN.setBorderPainted(false);
        cancelBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBTNActionPerformed(evt);
            }
        });

        backBTN1.setBackground(new java.awt.Color(235, 142, 39));
        backBTN1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        backBTN1.setForeground(new java.awt.Color(255, 255, 255));
        backBTN1.setText("RETURN TO MAIN PAGE");
        backBTN1.setBorder(null);
        backBTN1.setBorderPainted(false);
        backBTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTN1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rateLBL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rateTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(hireDateTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(positionLBL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(positionTF, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(phoneNoLBL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(phoneNoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(emailLBL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(addressLBL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addressTF, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(idLBL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(idTF, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lNameLBL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(fNameLBL)
                                .addGap(55, 55, 55)
                                .addComponent(fNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backBTN1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hireDateLBL)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(editBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(saveBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cancelBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fNameLBL)
                    .addComponent(fNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNameLBL)
                    .addComponent(lNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLBL)
                    .addComponent(idTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneNoLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneNoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(positionLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(positionTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rateLBL))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hireDateLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hireDateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(backBTN1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1002, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 695, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadForm(){
        fNameTF.setText(employeeInfo.getfName().toUpperCase());
        lNameTF.setText(employeeInfo.getlName().toUpperCase());
        idTF.setText(Integer.toString(employeeInfo.getId()));
        addressTF.setText(employeeInfo.getAddress().toUpperCase());
        emailTF.setText(employeeInfo.getEmail().toUpperCase());
        phoneNoTF.setText(employeeInfo.getPhoneNo());
        positionTF.setText(employeeInfo.getRole().toUpperCase());
        rateTF.setText(Double.toString(employeeInfo.getRate()) + "€/h");
        hireDateTF.setText(employeeInfo.getHireDate());
    }
    
    private void addressTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressTFActionPerformed

    private void idTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTFActionPerformed

    private void phoneNoTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNoTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNoTFActionPerformed

    private void fNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fNameTFActionPerformed

    private void emailTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTFActionPerformed

    private void positionTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_positionTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_positionTFActionPerformed

    private void rateTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rateTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rateTFActionPerformed

    private void hireDateTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hireDateTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hireDateTFActionPerformed

    private void resetForm(){
        cancelBTN.setVisible(false);
        saveBTN.setVisible(false);
        fNameTF.setEditable(false);
        lNameTF.setEditable(false);
        addressTF.setEditable(false);
        emailTF.setEditable(false);
        phoneNoTF.setEditable(false);
        fNameTF.setBackground(new java.awt.Color(255,255,255));
        lNameTF.setBackground(new java.awt.Color(255,255,255));
        addressTF.setBackground(new java.awt.Color(255,255,255));
        emailTF.setBackground(new java.awt.Color(255,255,255));
        phoneNoTF.setBackground(new java.awt.Color(255,255,255));
    }
    
    private void editBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBTNActionPerformed
        saveBTN.setVisible(true);
        cancelBTN.setVisible(true);
        addressTF.setEditable(true);
        emailTF.setEditable(true);
        phoneNoTF.setEditable(true);
        addressTF.setBackground(new java.awt.Color(242,242,242));
        emailTF.setBackground(new java.awt.Color(242,242,242));
        phoneNoTF.setBackground(new java.awt.Color(242,242,242));    
    }//GEN-LAST:event_editBTNActionPerformed

    private void lNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lNameTFActionPerformed

    private void saveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBTNActionPerformed
        updater.saveInfo(Integer.parseInt(idTF.getText()), fNameTF.getText(), lNameTF.getText(), addressTF.getText(), emailTF.getText(), phoneNoTF.getText());
        resetForm();
        JOptionPane.showMessageDialog(null, "Information saved successfully");
    }//GEN-LAST:event_saveBTNActionPerformed

    private void focusColour(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_focusColour

        
    }//GEN-LAST:event_focusColour

    private void cancelBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBTNActionPerformed
        resetForm();
    }//GEN-LAST:event_cancelBTNActionPerformed

    private void backBTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTN1ActionPerformed
        PayrollGUI pg = new PayrollGUI();
        pg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBTN1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditEmployeeInfoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditEmployeeInfoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditEmployeeInfoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditEmployeeInfoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditEmployeeInfoGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLBL;
    private javax.swing.JTextField addressTF;
    private javax.swing.JButton backBTN;
    private javax.swing.JButton backBTN1;
    private javax.swing.JButton cancelBTN;
    private javax.swing.JButton editBTN;
    private javax.swing.JLabel emailLBL;
    private javax.swing.JTextField emailTF;
    private javax.swing.JLabel fNameLBL;
    private javax.swing.JTextField fNameTF;
    private javax.swing.JLabel hireDateLBL;
    private javax.swing.JTextField hireDateTF;
    private javax.swing.JLabel iconLBL;
    private javax.swing.JLabel idLBL;
    private javax.swing.JTextField idTF;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lNameLBL;
    private javax.swing.JTextField lNameTF;
    private javax.swing.JLabel phoneNoLBL;
    private javax.swing.JTextField phoneNoTF;
    private javax.swing.JLabel positionLBL;
    private javax.swing.JTextField positionTF;
    private javax.swing.JLabel rateLBL;
    private javax.swing.JTextField rateTF;
    private javax.swing.JButton saveBTN;
    private javax.swing.JLabel subtitleLBL;
    private javax.swing.JLabel titleLBL;
    // End of variables declaration//GEN-END:variables
}
