/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package payrollsystem;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;

/**
 * DatabaseManager.java February 2025
 * @author Murilo Batiuk
 */
public class EmployeeSalaryGUI extends javax.swing.JFrame {

    private final EmployeeInfo employeeInfo = EmployeeInfo.getInstance();
    private final JTable financeTable;
    private final SalaryAdmin salaryAdmin;
    private final EmployeeDataFetcher dataFetcher = new EmployeeDataFetcher();
    private final SalaryAdmin Admin = new SalaryAdmin();

    /**
     * Creates new form PayrollGUI
     */
    public EmployeeSalaryGUI() {
        initComponents();

        dataFetcher.loadUserInformation("employee_id", "employee_logins", "employees");

        salaryAdmin = new SalaryAdmin();

        String[] columnNames = {"Week", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday", "Total Hours", "Total After Taxes"};
        financeTable = new JTable(new DefaultTableModel(columnNames, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        maintitleLBL = new javax.swing.JLabel();
        orangelogoLBL = new javax.swing.JLabel();
        jPanel = new javax.swing.JPanel();
        returnBTN = new javax.swing.JButton();
        selectmonthLBL = new javax.swing.JLabel();
        tblSCRLPN = new javax.swing.JScrollPane();
        weektableTBL = new javax.swing.JTable();
        januaryBTN = new javax.swing.JButton();
        februaryBTN = new javax.swing.JButton();
        marchBTN = new javax.swing.JButton();
        aprilBTN = new javax.swing.JButton();
        mayBTN = new javax.swing.JButton();
        juneBTN = new javax.swing.JButton();
        julyBTN = new javax.swing.JButton();
        augustBTN = new javax.swing.JButton();
        septemberBTN = new javax.swing.JButton();
        octoberBTN = new javax.swing.JButton();
        novemberBTN = new javax.swing.JButton();
        decemberBTN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));

        jPanel1.setBackground(new java.awt.Color(235, 142, 39));

        maintitleLBL.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        maintitleLBL.setForeground(new java.awt.Color(255, 255, 255));
        maintitleLBL.setText("ESTIMATED SALARY");

        orangelogoLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payrollsystem/PAYROLL_LOGO_E.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(maintitleLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 974, Short.MAX_VALUE)
                .addComponent(orangelogoLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(orangelogoLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(maintitleLBL)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel.setBackground(new java.awt.Color(255, 255, 255));
        jPanel.setFocusTraversalPolicyProvider(true);
        jPanel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jPanel.setPreferredSize(new java.awt.Dimension(1513, 1513));

        returnBTN.setBackground(new java.awt.Color(235, 142, 39));
        returnBTN.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        returnBTN.setForeground(new java.awt.Color(255, 255, 255));
        returnBTN.setText("RETURN TO DASHBOARD");
        returnBTN.setBorder(null);
        returnBTN.setBorderPainted(false);
        returnBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBTNActionPerformed(evt);
            }
        });

        selectmonthLBL.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        selectmonthLBL.setText("select month:");

        weektableTBL.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        weektableTBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "week", "monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday", "week total (€)", "total after taxes (€)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        weektableTBL.setRowHeight(60);
        tblSCRLPN.setViewportView(weektableTBL);

        januaryBTN.setBackground(new java.awt.Color(235, 142, 39));
        januaryBTN.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        januaryBTN.setForeground(new java.awt.Color(255, 255, 255));
        januaryBTN.setText("january");
        januaryBTN.setBorder(null);
        januaryBTN.setBorderPainted(false);
        januaryBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                januaryBTNActionPerformed(evt);
            }
        });

        februaryBTN.setBackground(new java.awt.Color(235, 142, 39));
        februaryBTN.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        februaryBTN.setForeground(new java.awt.Color(255, 255, 255));
        februaryBTN.setText("february");
        februaryBTN.setBorder(null);
        februaryBTN.setBorderPainted(false);
        februaryBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                februaryBTNActionPerformed(evt);
            }
        });

        marchBTN.setBackground(new java.awt.Color(235, 142, 39));
        marchBTN.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        marchBTN.setForeground(new java.awt.Color(255, 255, 255));
        marchBTN.setText("march");
        marchBTN.setBorder(null);
        marchBTN.setBorderPainted(false);
        marchBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marchBTNActionPerformed(evt);
            }
        });

        aprilBTN.setBackground(new java.awt.Color(235, 142, 39));
        aprilBTN.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        aprilBTN.setForeground(new java.awt.Color(255, 255, 255));
        aprilBTN.setText("april");
        aprilBTN.setBorder(null);
        aprilBTN.setBorderPainted(false);
        aprilBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aprilBTNActionPerformed(evt);
            }
        });

        mayBTN.setBackground(new java.awt.Color(235, 142, 39));
        mayBTN.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        mayBTN.setForeground(new java.awt.Color(255, 255, 255));
        mayBTN.setText("may");
        mayBTN.setBorder(null);
        mayBTN.setBorderPainted(false);
        mayBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mayBTNActionPerformed(evt);
            }
        });

        juneBTN.setBackground(new java.awt.Color(235, 142, 39));
        juneBTN.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        juneBTN.setForeground(new java.awt.Color(255, 255, 255));
        juneBTN.setText("june");
        juneBTN.setBorder(null);
        juneBTN.setBorderPainted(false);
        juneBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                juneBTNActionPerformed(evt);
            }
        });

        julyBTN.setBackground(new java.awt.Color(235, 142, 39));
        julyBTN.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        julyBTN.setForeground(new java.awt.Color(255, 255, 255));
        julyBTN.setText("july");
        julyBTN.setBorder(null);
        julyBTN.setBorderPainted(false);
        julyBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                julyBTNActionPerformed(evt);
            }
        });

        augustBTN.setBackground(new java.awt.Color(235, 142, 39));
        augustBTN.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        augustBTN.setForeground(new java.awt.Color(255, 255, 255));
        augustBTN.setText("august");
        augustBTN.setBorder(null);
        augustBTN.setBorderPainted(false);
        augustBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                augustBTNActionPerformed(evt);
            }
        });

        septemberBTN.setBackground(new java.awt.Color(235, 142, 39));
        septemberBTN.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        septemberBTN.setForeground(new java.awt.Color(255, 255, 255));
        septemberBTN.setText("september");
        septemberBTN.setBorder(null);
        septemberBTN.setBorderPainted(false);
        septemberBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                septemberBTNActionPerformed(evt);
            }
        });

        octoberBTN.setBackground(new java.awt.Color(235, 142, 39));
        octoberBTN.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        octoberBTN.setForeground(new java.awt.Color(255, 255, 255));
        octoberBTN.setText("october");
        octoberBTN.setBorder(null);
        octoberBTN.setBorderPainted(false);
        octoberBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                octoberBTNActionPerformed(evt);
            }
        });

        novemberBTN.setBackground(new java.awt.Color(235, 142, 39));
        novemberBTN.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        novemberBTN.setForeground(new java.awt.Color(255, 255, 255));
        novemberBTN.setText("november");
        novemberBTN.setBorder(null);
        novemberBTN.setBorderPainted(false);
        novemberBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novemberBTNActionPerformed(evt);
            }
        });

        decemberBTN.setBackground(new java.awt.Color(235, 142, 39));
        decemberBTN.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        decemberBTN.setForeground(new java.awt.Color(255, 255, 255));
        decemberBTN.setText("december");
        decemberBTN.setBorder(null);
        decemberBTN.setBorderPainted(false);
        decemberBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decemberBTNActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(81, 81, 81));
        jLabel1.setText("Please choose a month:");

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(selectmonthLBL)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(decemberBTN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(novemberBTN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(octoberBTN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(septemberBTN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(augustBTN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(julyBTN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(aprilBTN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(februaryBTN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(januaryBTN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(marchBTN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mayBTN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(juneBTN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(returnBTN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addComponent(tblSCRLPN, javax.swing.GroupLayout.PREFERRED_SIZE, 1097, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(selectmonthLBL)
                .addGap(118, 118, 118)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addComponent(tblSCRLPN, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addComponent(januaryBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(februaryBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(marchBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(aprilBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mayBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(juneBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(julyBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(augustBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(septemberBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(octoberBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(novemberBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(decemberBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                        .addComponent(returnBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1512, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 644, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void decemberBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decemberBTNActionPerformed
        // TODO add your handling code here:

        loadFinanceData(12);

    }//GEN-LAST:event_decemberBTNActionPerformed

    private void novemberBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novemberBTNActionPerformed
        // TODO add your handling code here:

        loadFinanceData(11);

    }//GEN-LAST:event_novemberBTNActionPerformed

    private void octoberBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_octoberBTNActionPerformed
        // TODO add your handling code here:

        loadFinanceData(10);

    }//GEN-LAST:event_octoberBTNActionPerformed

    private void septemberBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_septemberBTNActionPerformed
        // TODO add your handling code here:

        loadFinanceData(9);

    }//GEN-LAST:event_septemberBTNActionPerformed

    private void augustBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_augustBTNActionPerformed
        // TODO add your handling code here:

        loadFinanceData(8);

    }//GEN-LAST:event_augustBTNActionPerformed

    private void julyBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_julyBTNActionPerformed
        // TODO add your handling code here:

        loadFinanceData(7);

    }//GEN-LAST:event_julyBTNActionPerformed

    private void juneBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_juneBTNActionPerformed
        // TODO add your handling code here:

        loadFinanceData(6);

    }//GEN-LAST:event_juneBTNActionPerformed

    private void mayBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mayBTNActionPerformed
        // TODO add your handling code here:

        loadFinanceData(5);

    }//GEN-LAST:event_mayBTNActionPerformed

    private void aprilBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aprilBTNActionPerformed
        // TODO add your handling code here:

        loadFinanceData(4);

    }//GEN-LAST:event_aprilBTNActionPerformed

    private void marchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marchBTNActionPerformed
        // TODO add your handling code here:

        loadFinanceData(3);

    }//GEN-LAST:event_marchBTNActionPerformed

    private void februaryBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_februaryBTNActionPerformed
        // TODO add your handling code here:

        loadFinanceData(2);

    }//GEN-LAST:event_februaryBTNActionPerformed

    private void januaryBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_januaryBTNActionPerformed
        // TODO add your handling code here:

        loadFinanceData(1);
    }//GEN-LAST:event_januaryBTNActionPerformed

    private void returnBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBTNActionPerformed
        // TODO add your handling code here:

        EmployeeGUI empDashboard = new EmployeeGUI();
        empDashboard.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_returnBTNActionPerformed

    private void loadFinanceData(int month) {

        int employeeId = employeeInfo.getId();
        List<Object[]> financeData = Admin.loadEmployeeFinance(employeeId, month);

        DefaultTableModel model = (DefaultTableModel) weektableTBL.getModel();
        model.setRowCount(0); 

        for (Object[] row : financeData) {
            model.addRow(row);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeSalaryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeSalaryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeSalaryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeSalaryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeSalaryGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aprilBTN;
    private javax.swing.JButton augustBTN;
    private javax.swing.JButton decemberBTN;
    private javax.swing.JButton februaryBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton januaryBTN;
    private javax.swing.JButton julyBTN;
    private javax.swing.JButton juneBTN;
    private javax.swing.JLabel maintitleLBL;
    private javax.swing.JButton marchBTN;
    private javax.swing.JButton mayBTN;
    private javax.swing.JButton novemberBTN;
    private javax.swing.JButton octoberBTN;
    private javax.swing.JLabel orangelogoLBL;
    private javax.swing.JButton returnBTN;
    private javax.swing.JLabel selectmonthLBL;
    private javax.swing.JButton septemberBTN;
    private javax.swing.JScrollPane tblSCRLPN;
    private javax.swing.JTable weektableTBL;
    // End of variables declaration//GEN-END:variables
}
