/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package payrollsystem;

import java.util.List;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 * DatabaseManager.java 
 * February 2025
 * @author Murilo Batiuk
 */
public class EmployeeSalaryGUI extends javax.swing.JFrame {

    private final EmployeeInfo employeeInfo = EmployeeInfo.getInstance();
    private final JTable financeTable;
    private final JComboBox<String> monthComboBox;
    private final SalaryAdmin salaryAdmin;
    private final EmployeeDataFetcher dataFetcher = new EmployeeDataFetcher();
    private final SalaryAdmin admin = new SalaryAdmin();

    /**
     * Creates new form PayrollGUI
     */
    public EmployeeSalaryGUI() {
        initComponents();

        dataFetcher.loadUserInformation("employee_id", "employee_logins", "employees");

        salaryAdmin = new SalaryAdmin();

        // Define JTable columns
        String[] columnNames = {"Week", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday", "Total Hours"};
        financeTable = new JTable(new DefaultTableModel(columnNames, 0));

        // Month selection dropdown
        monthComboBox = new JComboBox<>(new String[]{"January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"});

        // Layout
        JPanel panel = new JPanel();
        panel.add(new JLabel("Select Month:"));
        panel.add(monthComboBox);
        add(panel, "North");
        add(new JScrollPane(financeTable), "Center");

        setTitle("Employee Salary");
        setSize(800, 400);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        returnBTN = new javax.swing.JButton();
        selectmonthCB = new javax.swing.JComboBox<>();
        selectmonthLBL = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        weektableTBL = new javax.swing.JTable();
        monthtotalLBL = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        monthtotalTA = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        maintitleLBL = new javax.swing.JLabel();
        orangelogoLBL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setFocusTraversalPolicyProvider(true);
        jPanel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(1513, 1513));

        returnBTN.setBackground(new java.awt.Color(235, 142, 39));
        returnBTN.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        returnBTN.setForeground(new java.awt.Color(255, 255, 255));
        returnBTN.setText("RETURN TO DASHBOARD");
        returnBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBTNActionPerformed(evt);
            }
        });

        selectmonthCB.setBackground(new java.awt.Color(235, 142, 39));
        selectmonthCB.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        selectmonthCB.setMaximumRowCount(12);
        selectmonthCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "january", "february", "march", "april", "may", "june", "july", "august", "september", "october", "november", "december" }));
        selectmonthCB.setBorder(null);
        selectmonthCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                january(evt);
                february(evt);
                march(evt);
                april(evt);
                may(evt);
                june(evt);
                july(evt);
                august(evt);
                september(evt);
                october(evt);
                november(evt);
                december(evt);
            }
        });

        selectmonthLBL.setBackground(new java.awt.Color(255, 255, 255));
        selectmonthLBL.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        selectmonthLBL.setText("select month:");

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        weektableTBL.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        weektableTBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "week", "monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday", "week total"
            }
        ));
        weektableTBL.setRowHeight(60);
        jScrollPane1.setViewportView(weektableTBL);

        monthtotalLBL.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        monthtotalLBL.setText("Month Total: ");

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        monthtotalTA.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        monthtotalTA.setAutoscrolls(false);
        jScrollPane2.setViewportView(monthtotalTA);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectmonthCB, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectmonthLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(99, 99, 99)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(monthtotalLBL)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(returnBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 898, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(selectmonthLBL)
                        .addGap(10, 10, 10)
                        .addComponent(selectmonthCB, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(monthtotalLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(returnBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(207, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(235, 142, 39));

        maintitleLBL.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        maintitleLBL.setForeground(new java.awt.Color(255, 255, 255));
        maintitleLBL.setText("ESTIMATED SALARY");

        orangelogoLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payrollsystem/PAYROLL_LOGO_E.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(maintitleLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 969, Short.MAX_VALUE)
                .addComponent(orangelogoLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(188, 188, 188))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(maintitleLBL))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(orangelogoLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1662, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void january(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_january
        // TODO add your handling code here:

        loadFinanceData(1);

    }//GEN-LAST:event_january

    private void february(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_february
        // TODO add your handling code here:

        loadFinanceData(2);
    }//GEN-LAST:event_february

    private void march(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_march
        // TODO add your handling code here:

        loadFinanceData(3);
    }//GEN-LAST:event_march

    private void april(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_april
        // TODO add your handling code here:

        loadFinanceData(4);
    }//GEN-LAST:event_april

    private void may(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_may
        // TODO add your handling code here:

        loadFinanceData(5);
    }//GEN-LAST:event_may

    private void june(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_june
        // TODO add your handling code here:

        loadFinanceData(6);
    }//GEN-LAST:event_june

    private void july(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_july
        // TODO add your handling code here:

        loadFinanceData(7);
    }//GEN-LAST:event_july

    private void august(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_august
        // TODO add your handling code here:

        loadFinanceData(8);
    }//GEN-LAST:event_august

    private void september(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_september
        // TODO add your handling code here:

        loadFinanceData(9);
    }//GEN-LAST:event_september

    private void october(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_october
        // TODO add your handling code here:

        loadFinanceData(10);
    }//GEN-LAST:event_october

    private void november(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_november
        // TODO add your handling code here:

        loadFinanceData(11);
    }//GEN-LAST:event_november

    private void december(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_december
        // TODO add your handling code here:

        loadFinanceData(12);
    }//GEN-LAST:event_december

    private void returnBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBTNActionPerformed
        EmployeeGUI empDashboard = new EmployeeGUI();
        empDashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_returnBTNActionPerformed

    private void loadFinanceData(int month) {
        int employeeId = employeeInfo.getId();  // Get employee ID
        List<Object[]> financeData = admin.loadEmployeeFinance(employeeId, month);

        DefaultTableModel model = (DefaultTableModel) weektableTBL.getModel();
        model.setRowCount(0);

        for (Object[] row : financeData) {
            model.addRow(row);
        }
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeSalaryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeSalaryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeSalaryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeSalaryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeSalaryGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel maintitleLBL;
    private javax.swing.JLabel monthtotalLBL;
    private javax.swing.JTextArea monthtotalTA;
    private javax.swing.JLabel orangelogoLBL;
    private javax.swing.JButton returnBTN;
    private javax.swing.JComboBox<String> selectmonthCB;
    private javax.swing.JLabel selectmonthLBL;
    private javax.swing.JTable weektableTBL;
    // End of variables declaration//GEN-END:variables
}
