/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package payrollsystem;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.*;

/**
 *
 * @author Stefany Junges
 */
public class LogInGUI extends javax.swing.JFrame {

    private boolean isManagerSelected = false;
    private boolean isEmployeeSelected = false;
    private ValidateLogin vl = new ValidateLogin();
    private SessionManager sm = SessionManager.getInstance();
    
    public LogInGUI() {
        initComponents();
        loadingDialog.setModal(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loadingDialog = new javax.swing.JDialog();
        dialogPanel1 = new javax.swing.JPanel();
        loadingLBL1 = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        loginLBL = new javax.swing.JLabel();
        managerBTN = new javax.swing.JButton();
        employeeBTN = new javax.swing.JButton();
        userLBL = new javax.swing.JLabel();
        passwordLBL = new javax.swing.JLabel();
        userTF = new javax.swing.JTextField();
        passwordTF = new javax.swing.JPasswordField();
        loginBTN = new javax.swing.JButton();
        forgotBTN = new javax.swing.JButton();
        detailsLBL = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        blueICON = new javax.swing.JLabel();
        orangeICON = new javax.swing.JLabel();
        showPassBTN = new javax.swing.JToggleButton();

        loadingDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        loadingDialog.setTitle("Loading...");

        dialogPanel1.setName(""); // NOI18N

        loadingLBL1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        loadingLBL1.setForeground(new java.awt.Color(81, 81, 81));
        loadingLBL1.setText("Loading...");

        progressBar.setIndeterminate(true);

        javax.swing.GroupLayout dialogPanel1Layout = new javax.swing.GroupLayout(dialogPanel1);
        dialogPanel1.setLayout(dialogPanel1Layout);
        dialogPanel1Layout.setHorizontalGroup(
            dialogPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogPanel1Layout.createSequentialGroup()
                .addGroup(dialogPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dialogPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(loadingLBL1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        dialogPanel1Layout.setVerticalGroup(
            dialogPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(loadingLBL1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout loadingDialogLayout = new javax.swing.GroupLayout(loadingDialog.getContentPane());
        loadingDialog.getContentPane().setLayout(loadingDialogLayout);
        loadingDialogLayout.setHorizontalGroup(
            loadingDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dialogPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        loadingDialogLayout.setVerticalGroup(
            loadingDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dialogPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        loginLBL.setFont(new java.awt.Font("Dialog", 1, 38)); // NOI18N
        loginLBL.setForeground(new java.awt.Color(81, 81, 81));
        loginLBL.setText("Log in");

        managerBTN.setBackground(new java.awt.Color(81, 81, 81));
        managerBTN.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        managerBTN.setForeground(new java.awt.Color(255, 255, 255));
        managerBTN.setText("MANAGER");
        managerBTN.setBorder(null);
        managerBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                managerBTNMousePressed(evt);
            }
        });
        managerBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managerBTNActionPerformed(evt);
            }
        });

        employeeBTN.setBackground(new java.awt.Color(81, 81, 81));
        employeeBTN.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        employeeBTN.setForeground(new java.awt.Color(255, 255, 255));
        employeeBTN.setText("EMPLOYEE");
        employeeBTN.setBorder(null);
        employeeBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                employeeBTNMousePressed(evt);
            }
        });
        employeeBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeBTNActionPerformed(evt);
            }
        });

        userLBL.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        userLBL.setForeground(new java.awt.Color(81, 81, 81));
        userLBL.setText("User");

        passwordLBL.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        passwordLBL.setForeground(new java.awt.Color(81, 81, 81));
        passwordLBL.setText("Password");

        passwordTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTFActionPerformed(evt);
            }
        });

        loginBTN.setBackground(new java.awt.Color(63, 0, 255));
        loginBTN.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        loginBTN.setForeground(new java.awt.Color(255, 255, 255));
        loginBTN.setText("LOG IN");
        loginBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBTNActionPerformed(evt);
            }
        });

        forgotBTN.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        forgotBTN.setForeground(new java.awt.Color(169, 169, 169));
        forgotBTN.setText("Forgot password?");
        forgotBTN.setBorder(null);
        forgotBTN.setBorderPainted(false);
        forgotBTN.setContentAreaFilled(false);
        forgotBTN.setFocusPainted(false);
        forgotBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                forgotBTNMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                forgotBTNMouseReleased(evt);
            }
        });
        forgotBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgotBTNActionPerformed(evt);
            }
        });

        detailsLBL.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        detailsLBL.setForeground(new java.awt.Color(169, 169, 169));
        detailsLBL.setText("Enter your details");

        jPanel2.setBackground(new java.awt.Color(248, 248, 248));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payrollsystem/laptop.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        blueICON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payrollsystem/smallogo.png"))); // NOI18N

        orangeICON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payrollsystem/smallogo2.png"))); // NOI18N

        showPassBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payrollsystem/eye.png"))); // NOI18N
        showPassBTN.setBorder(null);
        showPassBTN.setBorderPainted(false);
        showPassBTN.setContentAreaFilled(false);
        showPassBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPassBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(orangeICON)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(blueICON))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(userLBL)
                                .addComponent(userTF, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(passwordLBL)
                                .addComponent(forgotBTN)
                                .addComponent(loginBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(loginLBL)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(managerBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(employeeBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(detailsLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(passwordTF, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(showPassBTN)))))
                .addContainerGap(382, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(managerBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(loginLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(detailsLBL)
                .addGap(18, 18, 18)
                .addComponent(userLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(passwordLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showPassBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(forgotBTN)
                .addGap(31, 31, 31)
                .addComponent(loginBTN)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(orangeICON)
                    .addComponent(blueICON))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void forgotBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgotBTNActionPerformed

        //Calling the GUI that handles resetting the password
        ResetPasswordGUI f = new ResetPasswordGUI();
        f.setVisible(true);
    }//GEN-LAST:event_forgotBTNActionPerformed

    private void forgotBTNMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotBTNMouseReleased

    }//GEN-LAST:event_forgotBTNMouseReleased

    private void forgotBTNMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotBTNMousePressed

    }//GEN-LAST:event_forgotBTNMousePressed

    private void loginBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBTNActionPerformed

        if (checkEmpty()) {
            loadingDialog.setSize(210, 100);
            loadingDialog.setLocationRelativeTo(null);
            SwingUtilities.invokeLater(() -> loadingDialog.setVisible(true));

            SwingWorker<Boolean, Void> worker = new SwingWorker<>() {
                @Override
                protected Boolean doInBackground() {
                    boolean verify = false; // Default to false

                    // Check user identity
                    if (isEmployeeSelected) {
                        verify = vl.checkCredentials("employee_logins", userTF.getText().trim(), new String(passwordTF.getPassword()));
                    } else if (isManagerSelected) {
                        verify = vl.checkCredentials("manager_logins", userTF.getText().trim(), new String(passwordTF.getPassword()));
                    }

                    return verify;
                }

                @Override
                protected void done() {
                    // Close the loading popup
                    SwingUtilities.invokeLater(() -> loadingDialog.dispose());

                    try {
                        boolean verify = get(); // Get result from doInBackground

                        if (verify) {
                            if (isEmployeeSelected){
                                sm.setUser(userTF.getText().trim());
                                EditEmployeeInfoGUI ei = new EditEmployeeInfoGUI();
                                ei.setVisible(true);
                                dispose();
                            } else {
                                // Successful login, set session and open Payroll GUI
                                sm.setUser(userTF.getText().trim());
                                PayrollGUI pg = new PayrollGUI();
                                pg.setVisible(true);
                                dispose();
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "Invalid username or password.", "Error", JOptionPane.ERROR_MESSAGE);
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "An error occurred during login.", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
            };

            worker.execute(); // Start the background task

        }
    }//GEN-LAST:event_loginBTNActionPerformed

    private void passwordTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTFActionPerformed

    private void employeeBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeBTNActionPerformed

        //For other methods to check if the employee button is selected or not
        isEmployeeSelected=true;
        isManagerSelected=false;
    }//GEN-LAST:event_employeeBTNActionPerformed

    private void employeeBTNMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeeBTNMousePressed

        //Changing the label and button color when employee button is pressed
        userLBL.setText("Employee Username");
        employeeBTN.setBackground(new Color(235,142,39));
        managerBTN.setBackground(new Color(81,81,81));
    }//GEN-LAST:event_employeeBTNMousePressed

    private void managerBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managerBTNActionPerformed

        //For other methods to check if the manager button is selected or not
        isManagerSelected=true;
        isEmployeeSelected=false;
    }//GEN-LAST:event_managerBTNActionPerformed

    private void managerBTNMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_managerBTNMousePressed

        //Changing the label and button color when manager button is selected
        userLBL.setText("Manager Username");
        managerBTN.setBackground(new Color(12,48,128));
        employeeBTN.setBackground(new Color(81,81,81));
    }//GEN-LAST:event_managerBTNMousePressed

    private void showPassBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPassBTNActionPerformed
       //If button is selected, show password
        if (showPassBTN.isSelected()) {
            passwordTF.setEchoChar((char) 0);
        } else {
            //If not, keep it hidden
            passwordTF.setEchoChar('•');
        }
    }//GEN-LAST:event_showPassBTNActionPerformed

    private boolean checkEmpty(){
    
        //Show message to user if form is empty
        if (userTF.getText().isEmpty() || new String(passwordTF.getPassword()).isEmpty()){
            JOptionPane.showMessageDialog(null, "Please fill in all the forms"); 
            return false;
        }
        
        //Show message to user if checkbox wasn't selected
        if (!isManagerSelected && !isEmployeeSelected) {
            JOptionPane.showMessageDialog(null, "Please select Manager or Employee"); 
            return false;
        }
        
        return true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogInGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogInGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogInGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogInGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogInGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel blueICON;
    private javax.swing.JLabel detailsLBL;
    private javax.swing.JPanel dialogPanel1;
    private javax.swing.JButton employeeBTN;
    private javax.swing.JButton forgotBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JDialog loadingDialog;
    private javax.swing.JLabel loadingLBL1;
    private javax.swing.JButton loginBTN;
    private javax.swing.JLabel loginLBL;
    private javax.swing.JButton managerBTN;
    private javax.swing.JLabel orangeICON;
    private javax.swing.JLabel passwordLBL;
    private javax.swing.JPasswordField passwordTF;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JToggleButton showPassBTN;
    private javax.swing.JLabel userLBL;
    private javax.swing.JTextField userTF;
    // End of variables declaration//GEN-END:variables
}
