/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package payrollsystem;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Stefany Junges
 */
public class LogInGUI extends javax.swing.JFrame {

    private boolean isManagerSelected = false;
    private boolean isEmployeeSelected = false;
    private ValidateLogin vl = new ValidateLogin();
    
    public LogInGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        blueSPRT = new javax.swing.JSeparator();
        orangeSPRT = new javax.swing.JSeparator();
        loginLBL = new javax.swing.JLabel();
        managerBTN = new javax.swing.JButton();
        employeeBTN = new javax.swing.JButton();
        userLBL = new javax.swing.JLabel();
        passwordLBL = new javax.swing.JLabel();
        userTF = new javax.swing.JTextField();
        passwordTF = new javax.swing.JPasswordField();
        loginBTN = new javax.swing.JButton();
        forgotBTN = new javax.swing.JButton();
        detailsLBL = new javax.swing.JLabel();
        blueICON = new javax.swing.JLabel();
        orangeICON = new javax.swing.JLabel();
        showPassBTN = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        blueSPRT.setForeground(new java.awt.Color(12, 48, 128));

        orangeSPRT.setForeground(new java.awt.Color(235, 142, 39));

        loginLBL.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        loginLBL.setForeground(new java.awt.Color(81, 81, 81));
        loginLBL.setText("Log in");

        managerBTN.setBackground(new java.awt.Color(81, 81, 81));
        managerBTN.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        managerBTN.setForeground(new java.awt.Color(255, 255, 255));
        managerBTN.setText("MANAGER");
        managerBTN.setBorder(null);
        managerBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                managerBTNMousePressed(evt);
            }
        });
        managerBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managerBTNActionPerformed(evt);
            }
        });

        employeeBTN.setBackground(new java.awt.Color(81, 81, 81));
        employeeBTN.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        employeeBTN.setForeground(new java.awt.Color(255, 255, 255));
        employeeBTN.setText("EMPLOYEE");
        employeeBTN.setBorder(null);
        employeeBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                employeeBTNMousePressed(evt);
            }
        });
        employeeBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeBTNActionPerformed(evt);
            }
        });

        userLBL.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        userLBL.setForeground(new java.awt.Color(81, 81, 81));
        userLBL.setText("User");

        passwordLBL.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        passwordLBL.setForeground(new java.awt.Color(81, 81, 81));
        passwordLBL.setText("Password");

        passwordTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTFActionPerformed(evt);
            }
        });

        loginBTN.setBackground(new java.awt.Color(63, 0, 255));
        loginBTN.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        loginBTN.setForeground(new java.awt.Color(255, 255, 255));
        loginBTN.setText("LOG IN");
        loginBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBTNActionPerformed(evt);
            }
        });

        forgotBTN.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        forgotBTN.setForeground(new java.awt.Color(169, 169, 169));
        forgotBTN.setText("Forgot password?");
        forgotBTN.setBorder(null);
        forgotBTN.setBorderPainted(false);
        forgotBTN.setContentAreaFilled(false);
        forgotBTN.setFocusPainted(false);
        forgotBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                forgotBTNMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                forgotBTNMouseReleased(evt);
            }
        });
        forgotBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgotBTNActionPerformed(evt);
            }
        });

        detailsLBL.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        detailsLBL.setForeground(new java.awt.Color(169, 169, 169));
        detailsLBL.setText("Enter your details");

        blueICON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payrollsystem/smallogo.png"))); // NOI18N

        orangeICON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payrollsystem/smallogo2.png"))); // NOI18N

        showPassBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payrollsystem/eye.png"))); // NOI18N
        showPassBTN.setBorder(null);
        showPassBTN.setBorderPainted(false);
        showPassBTN.setContentAreaFilled(false);
        showPassBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPassBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(orangeICON)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(blueICON)
                .addGap(744, 744, 744))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(orangeSPRT, javax.swing.GroupLayout.PREFERRED_SIZE, 767, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(611, 611, 611)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(forgotBTN)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(passwordLBL)
                                        .addComponent(loginLBL)
                                        .addComponent(userLBL)
                                        .addComponent(userTF)
                                        .addComponent(passwordTF)
                                        .addComponent(loginBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(managerBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(employeeBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(showPassBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(detailsLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(354, 354, 354)
                            .addComponent(blueSPRT, javax.swing.GroupLayout.PREFERRED_SIZE, 767, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(399, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(blueSPRT, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orangeSPRT, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(managerBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(loginLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(detailsLBL)
                .addGap(18, 18, 18)
                .addComponent(userLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passwordLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showPassBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(forgotBTN)
                .addGap(30, 30, 30)
                .addComponent(loginBTN)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(orangeICON)
                    .addComponent(blueICON))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void managerBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managerBTNActionPerformed
        
        //For other methods to check if the manager button is selected or not
        isManagerSelected=true;
        isEmployeeSelected=false;
        
    }//GEN-LAST:event_managerBTNActionPerformed

    private void passwordTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTFActionPerformed

    private void employeeBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeBTNActionPerformed
      
        //For other methods to check if the employee button is selected or not
        isEmployeeSelected=true;
        isManagerSelected=false;
        
    }//GEN-LAST:event_employeeBTNActionPerformed

    private void forgotBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgotBTNActionPerformed

        //Calling the GUI that handles resetting the password
        ForgotPasswordGUI f = new ForgotPasswordGUI();
        f.setVisible(true);
        
    }//GEN-LAST:event_forgotBTNActionPerformed

    private boolean checkEmpty(){
    
        //Show message to user if form is empty
        if (userTF.getText().isEmpty() || new String(passwordTF.getPassword()).isEmpty()){
            JOptionPane.showMessageDialog(null, "Please fill in all the forms"); 
            return false;
        }
        
        //Show message to user if checkbox wasn't selected
        if (!isManagerSelected && !isEmployeeSelected) {
            JOptionPane.showMessageDialog(null, "Please select Manager or Employee"); 
            return false;
        }
        
        return true;
    }

    private void loginBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBTNActionPerformed

        //If all form is filled, proceed
        if (checkEmpty()){   
            //Using a boolean to check if identity was verified
            boolean verify = true;

            //Passing values to the method that handles identity checking
            if (isEmployeeSelected){
                verify = vl.checkCredentials("employee_logins", userTF.getText().trim(), new String(passwordTF.getPassword()));
            } else if (isManagerSelected){
                verify = vl.checkCredentials("manager_logins", userTF.getText().trim(), new String(passwordTF.getPassword()));
            }

            //Depending on whether the identity has been verified or not, show message to user
            if (verify){
                PayrollGUI p = new PayrollGUI();
                p.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Invalid username or password.");
            }
        }
    }//GEN-LAST:event_loginBTNActionPerformed

    private void managerBTNMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_managerBTNMousePressed

        //Changing the label and button color when manager button is selected
        userLBL.setText("Manager Username");
        managerBTN.setBackground(new Color(12,48,128));
        employeeBTN.setBackground(new Color(81,81,81));
        
    }//GEN-LAST:event_managerBTNMousePressed

    private void employeeBTNMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeeBTNMousePressed

        //Changing the label and button color when employee button is pressed        
        userLBL.setText("Employee Username");
        employeeBTN.setBackground(new Color(235,142,39));
        managerBTN.setBackground(new Color(81,81,81));
        
    }//GEN-LAST:event_employeeBTNMousePressed

    private void forgotBTNMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotBTNMousePressed

  
    }//GEN-LAST:event_forgotBTNMousePressed

    private void forgotBTNMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotBTNMouseReleased
       
        
    }//GEN-LAST:event_forgotBTNMouseReleased

    private void showPassBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPassBTNActionPerformed
        //If button is selected, show password
        if (showPassBTN.isSelected()) {
            passwordTF.setEchoChar((char) 0);
        } else {
            //If not, keep it hidden
            passwordTF.setEchoChar('•');
        }
    }//GEN-LAST:event_showPassBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogInGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogInGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogInGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogInGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogInGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel blueICON;
    private javax.swing.JSeparator blueSPRT;
    private javax.swing.JLabel detailsLBL;
    private javax.swing.JButton employeeBTN;
    private javax.swing.JButton forgotBTN;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginBTN;
    private javax.swing.JLabel loginLBL;
    private javax.swing.JButton managerBTN;
    private javax.swing.JLabel orangeICON;
    private javax.swing.JSeparator orangeSPRT;
    private javax.swing.JLabel passwordLBL;
    private javax.swing.JPasswordField passwordTF;
    private javax.swing.JToggleButton showPassBTN;
    private javax.swing.JLabel userLBL;
    private javax.swing.JTextField userTF;
    // End of variables declaration//GEN-END:variables
}
