package payrollsystem;

import java.awt.FontMetrics;

/**
 *
 * @author Filip
 */
public class ManagerDashboard extends javax.swing.JFrame {

    private EmployeeDataFetcher dataFetcher = new EmployeeDataFetcher();
    private EmployeeInfo employeeInfo = EmployeeInfo.getInstance();
    
    public ManagerDashboard() {
        initComponents();
        dataFetcher.loadUserInformation("manager_id", "manager_logins", "managers");
        mngNameLBL.setText(employeeInfo.getName() + "!");
        formatWelcome();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        iconLBL = new javax.swing.JLabel();
        titleLBL = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        menuPNL = new javax.swing.JPanel();
        reportBTN = new javax.swing.JButton();
        subtitleLBL = new javax.swing.JLabel();
        mngNameLBL = new javax.swing.JLabel();
        questionLBL = new javax.swing.JLabel();
        reviewBTN = new javax.swing.JButton();
        manageBTN = new javax.swing.JButton();
        holidayBTN = new javax.swing.JButton();
        logOutBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));

        jPanel1.setBackground(new java.awt.Color(12, 48, 128));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        iconLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payrollsystem/PAYROLL_LOGO_m.png"))); // NOI18N

        titleLBL.setBackground(new java.awt.Color(248, 248, 248));
        titleLBL.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        titleLBL.setForeground(new java.awt.Color(248, 248, 248));
        titleLBL.setText("DASHBOARD");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titleLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(575, 575, 575)
                .addComponent(iconLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                .addComponent(iconLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(titleLBL)
                .addGap(61, 61, 61))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(1920, 1080));

        menuPNL.setBackground(new java.awt.Color(248, 248, 248));

        reportBTN.setBackground(new java.awt.Color(33, 118, 206));
        reportBTN.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        reportBTN.setForeground(new java.awt.Color(255, 255, 255));
        reportBTN.setText("generate financial report");
        reportBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportBTNActionPerformed(evt);
            }
        });

        subtitleLBL.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        subtitleLBL.setForeground(new java.awt.Color(80, 80, 80));
        subtitleLBL.setText("Welcome back,");

        mngNameLBL.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        mngNameLBL.setForeground(new java.awt.Color(80, 80, 80));
        mngNameLBL.setText("Manager");

        questionLBL.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        questionLBL.setText("How can we help you today?");

        reviewBTN.setBackground(new java.awt.Color(33, 118, 206));
        reviewBTN.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        reviewBTN.setForeground(new java.awt.Color(255, 255, 255));
        reviewBTN.setText("review hours submission");
        reviewBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reviewBTNActionPerformed(evt);
            }
        });

        manageBTN.setBackground(new java.awt.Color(33, 118, 206));
        manageBTN.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        manageBTN.setForeground(new java.awt.Color(255, 255, 255));
        manageBTN.setText("manage employee");
        manageBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageBTNActionPerformed(evt);
            }
        });

        holidayBTN.setBackground(new java.awt.Color(33, 118, 206));
        holidayBTN.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        holidayBTN.setForeground(new java.awt.Color(255, 255, 255));
        holidayBTN.setText("manage holidays");
        holidayBTN.setPreferredSize(new java.awt.Dimension(127, 26));
        holidayBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                holidayBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPNLLayout = new javax.swing.GroupLayout(menuPNL);
        menuPNL.setLayout(menuPNLLayout);
        menuPNLLayout.setHorizontalGroup(
            menuPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPNLLayout.createSequentialGroup()
                .addGroup(menuPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuPNLLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(subtitleLBL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mngNameLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menuPNLLayout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(questionLBL))
                    .addGroup(menuPNLLayout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addGroup(menuPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(reviewBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(manageBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(holidayBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reportBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        menuPNLLayout.setVerticalGroup(
            menuPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPNLLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(menuPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mngNameLBL)
                    .addComponent(subtitleLBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(questionLBL)
                .addGap(55, 55, 55)
                .addComponent(manageBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reviewBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(holidayBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reportBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        logOutBTN.setBackground(new java.awt.Color(33, 118, 206));
        logOutBTN.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        logOutBTN.setForeground(new java.awt.Color(255, 255, 255));
        logOutBTN.setText("LOG OUT");
        logOutBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(441, 441, 441)
                        .addComponent(menuPNL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(703, 703, 703)
                        .addComponent(logOutBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(menuPNL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logOutBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1579, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 795, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formatWelcome(){
        FontMetrics metrics = mngNameLBL.getFontMetrics(mngNameLBL.getFont());
        int nameWidth = metrics.stringWidth(mngNameLBL.getText());

        // Get panel width (or parent container width)
        int panelWidth = menuPNL.getWidth();

        // Calculate new positions
        int welcomeX = (panelWidth - (nameWidth + subtitleLBL.getWidth() + 10)) / 2; // Adjust spacing
        int nameX = welcomeX + subtitleLBL.getWidth() + 5; // Small gap between labels

        // Apply new positions
        subtitleLBL.setLocation(welcomeX, subtitleLBL.getY());
        subtitleLBL.setLocation(nameX, subtitleLBL.getY());
    }
    
    private void reviewBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reviewBTNActionPerformed
        SubmissionApprovalGUI submissionApproval = new SubmissionApprovalGUI();
        submissionApproval.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_reviewBTNActionPerformed

    private void holidayBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_holidayBTNActionPerformed
        HolidayApprovalGUI holidayApproval = new HolidayApprovalGUI();
        holidayApproval.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_holidayBTNActionPerformed

    private void manageBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageBTNActionPerformed
        // TODO add your handling code here:
          ManageEmployee manageFrame = new ManageEmployee();
          manageFrame.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_manageBTNActionPerformed

    private void reportBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportBTNActionPerformed
        FinancialReportGUI financialReport = new FinancialReportGUI();
        financialReport.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_reportBTNActionPerformed

    private void logOutBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutBTNActionPerformed
        SessionManager.getInstance().clearSession();
        LogInGUI login = new LogInGUI();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logOutBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton holidayBTN;
    private javax.swing.JLabel iconLBL;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton logOutBTN;
    private javax.swing.JButton manageBTN;
    private javax.swing.JPanel menuPNL;
    private javax.swing.JLabel mngNameLBL;
    private javax.swing.JLabel questionLBL;
    private javax.swing.JButton reportBTN;
    private javax.swing.JButton reviewBTN;
    private javax.swing.JLabel subtitleLBL;
    private javax.swing.JLabel titleLBL;
    // End of variables declaration//GEN-END:variables
}
