/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package payrollsystem;
import javax.swing.JOptionPane;

/**
 * @author Stefany Junges
 */

public class ResetPasswordGUI extends javax.swing.JFrame {
   
    //Calling a new instance of PasswordManager class
    private PasswordManager rp = new PasswordManager();
    
    public ResetPasswordGUI() {
        initComponents();
        //Setting elements to be invisible when window opens
        newPassLBL.setVisible(false);
        newPassTF.setVisible(false);
        submitBTN.setVisible(false);
        showPassBTN.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        resetLBL = new javax.swing.JLabel();
        idLBL = new javax.swing.JLabel();
        usernameTF = new javax.swing.JTextField();
        verifyBTN = new javax.swing.JButton();
        detailsLBL = new javax.swing.JLabel();
        usernameLBL = new javax.swing.JLabel();
        idTF = new javax.swing.JTextField();
        imLBL = new javax.swing.JLabel();
        employeeCB = new javax.swing.JCheckBox();
        managerCB = new javax.swing.JCheckBox();
        newPassLBL = new javax.swing.JLabel();
        infoTA = new javax.swing.JTextArea();
        submitBTN = new javax.swing.JButton();
        newPassTF = new javax.swing.JPasswordField();
        showPassBTN = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        resetLBL.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        resetLBL.setForeground(new java.awt.Color(81, 81, 81));
        resetLBL.setText("Reset your password");

        idLBL.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        idLBL.setForeground(new java.awt.Color(81, 81, 81));
        idLBL.setText("ID");

        usernameTF.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        verifyBTN.setBackground(new java.awt.Color(63, 0, 255));
        verifyBTN.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        verifyBTN.setForeground(new java.awt.Color(255, 255, 255));
        verifyBTN.setText("VERIFY");
        verifyBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifyBTNActionPerformed(evt);
            }
        });

        detailsLBL.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        detailsLBL.setForeground(new java.awt.Color(169, 169, 169));
        detailsLBL.setText("Verify your identity.");

        usernameLBL.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        usernameLBL.setForeground(new java.awt.Color(81, 81, 81));
        usernameLBL.setText("Username");

        imLBL.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        imLBL.setForeground(new java.awt.Color(81, 81, 81));
        imLBL.setText("I'm a");

        employeeCB.setBackground(new java.awt.Color(255, 255, 255));
        btnGroup.add(employeeCB);
        employeeCB.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        employeeCB.setForeground(new java.awt.Color(81, 81, 81));
        employeeCB.setText("Employee");

        managerCB.setBackground(new java.awt.Color(255, 255, 255));
        btnGroup.add(managerCB);
        managerCB.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        managerCB.setForeground(new java.awt.Color(81, 81, 81));
        managerCB.setText("Manager");

        newPassLBL.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        newPassLBL.setForeground(new java.awt.Color(81, 81, 81));
        newPassLBL.setText("New password:");

        infoTA.setColumns(20);
        infoTA.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        infoTA.setForeground(new java.awt.Color(81, 81, 81));
        infoTA.setLineWrap(true);
        infoTA.setRows(5);
        infoTA.setBorder(null);

        submitBTN.setBackground(new java.awt.Color(63, 0, 255));
        submitBTN.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        submitBTN.setForeground(new java.awt.Color(255, 255, 255));
        submitBTN.setText("SUBMIT");
        submitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBTNActionPerformed(evt);
            }
        });

        newPassTF.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        showPassBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payrollsystem/eye.png"))); // NOI18N
        showPassBTN.setBorder(null);
        showPassBTN.setBorderPainted(false);
        showPassBTN.setContentAreaFilled(false);
        showPassBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPassBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usernameTF)
                            .addComponent(idTF)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(usernameLBL)
                                    .addComponent(idLBL)
                                    .addComponent(resetLBL)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(imLBL)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(managerCB, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(employeeCB, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(detailsLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(verifyBTN)
                                    .addComponent(newPassLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(newPassTF, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(showPassBTN)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(infoTA, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(submitBTN))
                        .addGap(0, 12, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(resetLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(detailsLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imLBL)
                    .addComponent(managerCB)
                    .addComponent(employeeCB))
                .addGap(18, 18, 18)
                .addComponent(idLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(usernameLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(verifyBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(infoTA, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newPassLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(newPassTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showPassBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(submitBTN)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void submitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBTNActionPerformed

        //Using a boolean to check if the password was updated or not
        boolean isUpdated = true;

        //Passing values to the method that handles password updates
        if (employeeCB.isSelected()){
            isUpdated = rp.updatePassword("employee_logins", "employee_id", idTF.getText(), usernameTF.getText(), newPassTF.getText());
        } else if (managerCB.isSelected()){
            isUpdated = rp.updatePassword("manager_logins", "manager_id", idTF.getText(), usernameTF.getText(), newPassTF.getText());
        } else {
            //If nothing was selected, show message to user
            JOptionPane.showMessageDialog(null, "Please choose Manager or Employee");
        }

        //Depending on whether password was successfully updated or not, show message to user
        if (isUpdated){
            JOptionPane.showMessageDialog(null, "Password updated.");
            //Close the window
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Error updating password. Please try again later.");
        }

    }//GEN-LAST:event_submitBTNActionPerformed

    private boolean checkEmpty(){
        //Show message to user if form is empty
        if (idTF.getText().isEmpty() || usernameTF.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please fill in all the forms.");
            return false;
        }
        
        //Show message to user if checkbox wasn't selected
        if (!employeeCB.isSelected() && !managerCB.isSelected()){
            JOptionPane.showMessageDialog(null, "Please choose Manager or Employee."); 
            return false;
        }
        
        return true;
    }
    
    private void verifyBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifyBTNActionPerformed
        
        //If all form is filled, proceed
        if (checkEmpty()){
            //Using a boolean to check if identity was verified
            boolean verify;
            
            //Passing values to the method that handles identity checking
            if (employeeCB.isSelected()){
                verify = rp.checkIdentity("employee_logins", "employee_id", idTF.getText().trim(), usernameTF.getText().trim());
            } else {
                verify = rp.checkIdentity("manager_logins", "manager_id", idTF.getText().trim(), usernameTF.getText().trim());
            }
            
            //Depending on whether the identity has been verified or not, show message to user
            if (verify){
                infoTA.setText("Thank you for verifying your identity.\n\nChoose your new password:");
                newPassLBL.setVisible(true);
                newPassTF.setVisible(true);
                submitBTN.setVisible(true);
                showPassBTN.setVisible(true);
            } else {
                infoTA.setText("Sorry, we couldn't verify your identity this time.\nTry again or contact PayrollPRO support:\nMon-Fri (9am-6pm) at 083-000-001");
                newPassLBL.setVisible(false);
                newPassTF.setVisible(false);
                submitBTN.setVisible(false);
                showPassBTN.setVisible(false);
            }
        }
    }//GEN-LAST:event_verifyBTNActionPerformed

    private void showPassBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPassBTNActionPerformed
        //If button is selected, show password
        if (showPassBTN.isSelected()) {
            newPassTF.setEchoChar((char) 0);
        } else {
            //If not, keep it hidden
            newPassTF.setEchoChar('•');
        }
    }//GEN-LAST:event_showPassBTNActionPerformed
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.JLabel detailsLBL;
    private javax.swing.JCheckBox employeeCB;
    private javax.swing.JLabel idLBL;
    private javax.swing.JTextField idTF;
    private javax.swing.JLabel imLBL;
    private javax.swing.JTextArea infoTA;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox managerCB;
    private javax.swing.JLabel newPassLBL;
    private javax.swing.JPasswordField newPassTF;
    private javax.swing.JLabel resetLBL;
    private javax.swing.JToggleButton showPassBTN;
    private javax.swing.JButton submitBTN;
    private javax.swing.JLabel usernameLBL;
    private javax.swing.JTextField usernameTF;
    private javax.swing.JButton verifyBTN;
    // End of variables declaration//GEN-END:variables
}
