/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package payrollsystem;

public class SubmissionApprovalGUI extends javax.swing.JFrame {

    private EmployeeDataFetcher dataFetcher = new EmployeeDataFetcher();
    private EmployeeInfo employeeInfo = EmployeeInfo.getInstance();
    private FinanceDataFetcher financeFetcher = new FinanceDataFetcher();
    private SubmissionManager submissionManager = new SubmissionManager();
    
    public SubmissionApprovalGUI() {
        initComponents();
        update();
        dataFetcher.loadUserInformation("manager_id", "manager_logins", "managers");
        financeFetcher.loadAllEmployeesFinance();
        sendRefreshBTN.setVisible(false);
        reasonTF.setVisible(false);
        reasonLBL.setVisible(false);
        subtitleLBL.setText("Hello, " + employeeInfo.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        titleLBL = new javax.swing.JLabel();
        subtitleLBL = new javax.swing.JLabel();
        iconLBL = new javax.swing.JLabel();
        empIdLBL = new javax.swing.JLabel();
        daysWorkedLBL = new javax.swing.JLabel();
        hoursWorkedLBL = new javax.swing.JLabel();
        approveBTN = new javax.swing.JButton();
        rejectBTN = new javax.swing.JButton();
        daysWorkedTF = new javax.swing.JTextField();
        empIdTF = new javax.swing.JTextField();
        hoursWorkedTF = new javax.swing.JTextField();
        warningLBL = new javax.swing.JLabel();
        reasonTF = new javax.swing.JTextArea();
        reasonLBL = new javax.swing.JLabel();
        sendRefreshBTN = new javax.swing.JButton();
        estSalaryLBL = new javax.swing.JLabel();
        estSalaryTF = new javax.swing.JTextField();
        backBTN = new javax.swing.JButton();
        empNameLBL = new javax.swing.JLabel();
        empNameTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 48, 128));

        titleLBL.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        titleLBL.setForeground(new java.awt.Color(255, 255, 255));
        titleLBL.setText("REVIEW SUBMISSIONS");

        subtitleLBL.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        subtitleLBL.setForeground(new java.awt.Color(255, 255, 255));
        subtitleLBL.setText("Hello,");

        iconLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payrollsystem/PAYROLL_LOGO_m.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLBL)
                    .addComponent(subtitleLBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 790, Short.MAX_VALUE)
                .addComponent(iconLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(147, 147, 147))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(iconLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(titleLBL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subtitleLBL)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        empIdLBL.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        empIdLBL.setText("EMPLOYEE ID:");

        daysWorkedLBL.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        daysWorkedLBL.setText("DAYS WORKED:");

        hoursWorkedLBL.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        hoursWorkedLBL.setText("HOURS WORKED:");

        approveBTN.setBackground(new java.awt.Color(0, 255, 0));
        approveBTN.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        approveBTN.setForeground(new java.awt.Color(255, 255, 255));
        approveBTN.setText("APPROVE");
        approveBTN.setBorder(null);
        approveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveBTNActionPerformed(evt);
            }
        });

        rejectBTN.setBackground(new java.awt.Color(255, 0, 0));
        rejectBTN.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        rejectBTN.setForeground(new java.awt.Color(255, 255, 255));
        rejectBTN.setText("REJECT");
        rejectBTN.setBorder(null);
        rejectBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rejectBTNActionPerformed(evt);
            }
        });

        daysWorkedTF.setEditable(false);
        daysWorkedTF.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        daysWorkedTF.setForeground(new java.awt.Color(81, 81, 81));
        daysWorkedTF.setBorder(null);
        daysWorkedTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daysWorkedTFActionPerformed(evt);
            }
        });

        empIdTF.setEditable(false);
        empIdTF.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        empIdTF.setForeground(new java.awt.Color(81, 81, 81));
        empIdTF.setBorder(null);
        empIdTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empIdTFActionPerformed(evt);
            }
        });

        hoursWorkedTF.setEditable(false);
        hoursWorkedTF.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        hoursWorkedTF.setForeground(new java.awt.Color(81, 81, 81));
        hoursWorkedTF.setBorder(null);
        hoursWorkedTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hoursWorkedTFActionPerformed(evt);
            }
        });

        warningLBL.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        warningLBL.setText("You have pending submissions to review for Week");

        reasonTF.setColumns(20);
        reasonTF.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        reasonTF.setForeground(new java.awt.Color(81, 81, 81));
        reasonTF.setLineWrap(true);
        reasonTF.setRows(5);
        reasonTF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(81, 81, 81)));

        reasonLBL.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        reasonLBL.setText("Reason for rejection:");

        sendRefreshBTN.setBackground(new java.awt.Color(33, 118, 206));
        sendRefreshBTN.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        sendRefreshBTN.setForeground(new java.awt.Color(255, 255, 255));
        sendRefreshBTN.setText("SEND");
        sendRefreshBTN.setBorder(null);
        sendRefreshBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendRefreshBTNActionPerformed(evt);
            }
        });

        estSalaryLBL.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        estSalaryLBL.setText("ESTIMATED SALARY:");

        estSalaryTF.setEditable(false);
        estSalaryTF.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        estSalaryTF.setForeground(new java.awt.Color(81, 81, 81));
        estSalaryTF.setBorder(null);
        estSalaryTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estSalaryTFActionPerformed(evt);
            }
        });

        backBTN.setBackground(new java.awt.Color(33, 118, 206));
        backBTN.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        backBTN.setForeground(new java.awt.Color(255, 255, 255));
        backBTN.setText("RETURN TO MAIN PAGE");
        backBTN.setBorder(null);
        backBTN.setBorderPainted(false);
        backBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTNActionPerformed(evt);
            }
        });

        empNameLBL.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        empNameLBL.setText("EMPLOYEE NAME:");

        empNameTF.setEditable(false);
        empNameTF.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        empNameTF.setForeground(new java.awt.Color(81, 81, 81));
        empNameTF.setBorder(null);
        empNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empNameTFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(warningLBL)
                    .addComponent(sendRefreshBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reasonLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(approveBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rejectBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(daysWorkedLBL)
                            .addComponent(empIdLBL)
                            .addComponent(empNameLBL)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(estSalaryLBL, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(hoursWorkedLBL)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hoursWorkedTF, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(estSalaryTF, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(daysWorkedTF, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(empIdTF, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(empNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(reasonTF))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(warningLBL)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empNameLBL)
                    .addComponent(empNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empIdLBL)
                    .addComponent(empIdTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(daysWorkedTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(daysWorkedLBL, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hoursWorkedTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hoursWorkedLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estSalaryLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estSalaryTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(approveBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rejectBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(reasonLBL)
                .addGap(12, 12, 12)
                .addComponent(reasonTF, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(sendRefreshBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(backBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hoursWorkedTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hoursWorkedTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hoursWorkedTFActionPerformed

    private void empIdTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empIdTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empIdTFActionPerformed

    private void daysWorkedTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daysWorkedTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_daysWorkedTFActionPerformed

    public void update() {

        HoursSubmissionData submissionData = submissionManager.loadStatus();

        if (submissionData.isPending()) {
            empNameTF.setText(submissionData.getEmployeeName());
            empIdTF.setText(String.valueOf(submissionData.getEmployeeId()));
            warningLBL.setText("You have pending submissions to review for Week " + submissionData.getWeekNumber());
            hoursWorkedTF.setText(String.valueOf(submissionData.getTotalHours()));
            estSalaryTF.setText(String.valueOf(submissionData.getSalary()));
            daysWorkedTF.setText(submissionData.getWorkedDays());

            empIdTF.setVisible(true);
            hoursWorkedTF.setVisible(true);
            estSalaryTF.setVisible(true);
            daysWorkedTF.setVisible(true);
            
        } else {
            warningLBL.setText("No pending approvals.");
            empNameTF.setVisible(false);
            empNameLBL.setVisible(false);
            empIdTF.setVisible(false);
            empIdLBL.setVisible(false);
            hoursWorkedTF.setVisible(false);
            hoursWorkedLBL.setVisible(false);
            estSalaryTF.setVisible(false);
            estSalaryLBL.setVisible(false);
            daysWorkedTF.setVisible(false);
            daysWorkedLBL.setVisible(false);
            approveBTN.setVisible(false);
            rejectBTN.setVisible(false);
        }
    }

    public void approveHours() {
        if (!empIdTF.getText().isEmpty()) {
            int employeeId = Integer.parseInt(empIdTF.getText());
            submissionManager.approveHours(employeeId);
            update();
        }
    }

    public void rejectHours() {
        if (!empIdTF.getText().isEmpty()) {
            int employeeId = Integer.parseInt(empIdTF.getText());
            submissionManager.rejectHours(employeeId);
            update();
        }
    }
    
    private void rejectBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejectBTNActionPerformed
        sendRefreshBTN.setVisible(true);
        reasonTF.setVisible(true);
        reasonLBL.setVisible(true);
    }//GEN-LAST:event_rejectBTNActionPerformed

    private void estSalaryTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estSalaryTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estSalaryTFActionPerformed

    private void approveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveBTNActionPerformed
        approveHours();
    }//GEN-LAST:event_approveBTNActionPerformed

    private void sendRefreshBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendRefreshBTNActionPerformed
       rejectHours();
       reasonTF.setVisible(false);
       reasonLBL.setVisible(false);
       sendRefreshBTN.setVisible(false);
    }//GEN-LAST:event_sendRefreshBTNActionPerformed

    private void backBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTNActionPerformed
        PayrollGUI pg = new PayrollGUI();
        pg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBTNActionPerformed

    private void empNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empNameTFActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubmissionApprovalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubmissionApprovalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubmissionApprovalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubmissionApprovalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SubmissionApprovalGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton approveBTN;
    private javax.swing.JButton backBTN;
    private javax.swing.JLabel daysWorkedLBL;
    private javax.swing.JTextField daysWorkedTF;
    private javax.swing.JLabel empIdLBL;
    private javax.swing.JTextField empIdTF;
    private javax.swing.JLabel empNameLBL;
    private javax.swing.JTextField empNameTF;
    private javax.swing.JLabel estSalaryLBL;
    private javax.swing.JTextField estSalaryTF;
    private javax.swing.JLabel hoursWorkedLBL;
    private javax.swing.JTextField hoursWorkedTF;
    private javax.swing.JLabel iconLBL;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel reasonLBL;
    private javax.swing.JTextArea reasonTF;
    private javax.swing.JButton rejectBTN;
    private javax.swing.JButton sendRefreshBTN;
    private javax.swing.JLabel subtitleLBL;
    private javax.swing.JLabel titleLBL;
    private javax.swing.JLabel warningLBL;
    // End of variables declaration//GEN-END:variables
}
